version: "3.7"
services:
  namenode:
    container_name: namenode
    build:
      context: ./hadoop
    ports: 
        - "9870:9870"
        - "8088:8088"
    command: > 
      bash -c "hdfs --daemon start namenode & yarn --daemon start resourcemanager & tail -f /dev/null"
    hostname: hdfs-namenode
    volumes:
      - namenode:/data/dfs/name
  
  datanode:
    container_name: datanode
    build:
      context: ./hadoop
    hostname: datanode
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs --daemon start datanode & yarn --daemon start nodemanager & tail -f /dev/null"
    ports:
      - "9864:9864"
    volumes:
      - datanode:/data/dfs/data

  secondarynamenode:
    container_name: secondarynamenode
    build:
      context: ./hadoop
    command: bash -c "hdfs --daemon start secondarynamenode & tail -f /dev/null"
    ports:
        - "9868:9868"
    volumes:
      - namesecondary:/data/dfs/namesecondary
  
  metastore-standalone:
    image: apache/hive:3.1.3
    container_name: metastore-standalone
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
    depends_on:
      - postgres
    volumes:
      - warehouse:/opt/hive/data/warehouse
  
  postgres:
    image: postgres:13.12
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  warehouse:
  namesecondary:
  namenode:
  datanode:
  postgres:
